services:
  gateway:
    container_name: gateway
    image: lexunok/gateway:latest
    environment:
      TZ: Europe/Yekaterinburg
      SERVICE_PASSWORD: password
      AUTH_URL: http://127.0.0.1:7777
      AUTH_URL_TOKEN: http://authorization-service:7777
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - 80:80
    networks:
      - spring
  authorization-service:
    container_name: authorization-service
    image: lexunok/authorization-service:latest
    environment:
      TZ: Europe/Yekaterinburg
      SERVICE_USERNAME: admin
      SERVICE_PASSWORD: password
      GATEWAY_URL: http://localhost
      AUTH_URL: http://127.0.0.1:7777
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - authorization:/data/authorization
    ports:
      - 7777:7777
    networks:
      - spring
  postgres-authorization:
    container_name: postgres-authorization
    image: postgres
    restart: always
    environment:
      TZ: Europe/Yekaterinburg
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: hits
    ports:
      - 5433:5432
    volumes:
      - postgres-authorization:/data/postgres-authorization
    networks:
      - spring
  postgres-ideas:
    container_name: postgres-ideas
    image: postgres
    restart: always
    environment:
      TZ: Europe/Yekaterinburg
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hits
    ports:
      - 5432:5432
    volumes:
      - postgres-ideas:/data/postgres-ideas
    networks:
      - spring
networks:
  spring:
    driver: bridge
volumes:
  authorization:
  postgres-authorization:
  postgres-ideas: