server:
    port: 7777
    admin:
        username: admin@admin.com
        password: password
file:
    path: "/data/auth"
spring:
    rabbitmq:
        addresses: localhost:5672
    datasource:
        url: jdbc:postgresql://localhost:5433/hits
        username: admin
        password: admin
    jpa:
        open-in-view: false
        show-sql: true
        properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
    data:
        redis:
            repositories:
                enabled: false
            host: localhost
            port: 6379
rabbitmq:
    exchanges:
        internal: internal.exchange
    routing-keys:
        internal-invitation: internal.invitation.routing-key
oauth:
    secret: secret
    redirect: http://localhost:3000/code
    issuer: http://localhost

