server:
    port: 7777
spring:
    rabbitmq:
        addresses: rabbitmq
    datasource:
        url: jdbc:postgresql://db-authorization/hits
        username: ${SERVICE_USERNAME}
        password: ${SERVICE_PASSWORD}
    jpa:
        show-sql: true
        properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
    data:
        redis:
            host: redis
            port: 6379
rabbitmq:
    exchanges:
        internal: internal.exchange
    routing-keys:
        internal-invitation: internal.invitation.routing-key
oauth:
    secret: ${SERVICE_PASSWORD}
    redirect: ${GATEWAY_URL}/login/oauth2/code/gateway
    issuer: ${AUTH_URL}

