server:
  port: 80
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie
      routes:
        - id: ideas-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/ideas-service/**
        - id: scrum-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/scrum-service/**
        - id: email-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/email-service/**
        - id: tgbot-service
          uri: http://localhost:7000
          predicates:
            - Path=/api/v1/tgbot-service/**
        - id: authorization-service
          uri: http://localhost:7777
          predicates:
            - Path=/auth/**, /oauth2/**, /api/v1/authorization-service/**
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: hits
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          spring:
            authorization-uri: http://localhost/oauth2/authorize
            token-uri: http://localhost/oauth2/token
            jwk-set-uri: http://localhost/oauth2/jwks
