server:
  port: 80
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie
      routes:
        - id: ideas-service
          uri: http://ideas-service:8082
          predicates:
            - Path=/api/v1/ideas-service/**
        - id: scrum-service
          uri: http://ideas-service:8082
          predicates:
            - Path=/api/v1/scrum-service/**
        - id: notification-service
          uri: http://notification-service:8083
          predicates:
            - Path=/api/v1/notification-service/**
        - id: email-service
          uri: http://email-service:8084
          predicates:
            - Path=/api/v1/email-service/**
        - id: tgbot-service
          uri: http://tgbot-service:7000
          predicates:
            - Path=/api/v1/tgbot-service/**
        - id: authorization-service
          uri: http://authorization-service:7777
          predicates:
            - Path=/api/v1/authorization-service/**
        - id: authorization-service-view
          uri: http://authorization-service:7777
          predicates:
            - Path=/auth/**
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: ${SERVICE_PASSWORD}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          spring:
            authorization-uri: ${AUTH_URL}/oauth2/authorize
            token-uri: ${AUTH_URL_TOKEN}/oauth2/token
            jwk-set-uri: ${AUTH_URL_TOKEN}/oauth2/jwks

