server:
  port: 80
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:7777"
              - "http://localhost:3000"
              - "https://hits.tyuiu.ru"
              - "https://hits1.tyuiu.ru"
              - "http://authorization-service:7777"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: ideas-service
          uri: http://ideas-service:8082
          predicates:
            - Path=/api/v1/ideas-service/**
        - id: quest-service
          uri: http://quest-service:5000
          predicates:
            - Path=/api/v1/quest-service/**
        - id: scrum-service
          uri: http://ideas-service:8082
          predicates:
            - Path=/api/v1/scrum-service/**
        - id: rsocket-comment-route
          uri: ws://localhost:7777
          predicates:
            - Path=/rs/**
          metadata:
            protocol: ws
        - id: email-service
          uri: http://email-service:8084
          predicates:
            - Path=/api/v1/email-service/**
        - id: tgbot-service
          uri: http://tgbot-service:7000
          predicates:
            - Path=/api/v1/tgbot-service/**
        - id: authorization-service
          uri: http://authorization-service:7777
          predicates:
            - Path=/api/v1/authorization-service/**, /auth/**, /oauth2/**
          filters:
            - RewriteResponseHeader=Location, , http://authorization-service:7777, ${GATEWAY}
