server:
  port: 80
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:7777"
              - "http://localhost:3000"
              - "https://hits.tyiu.ru"
              - "http://authorization-service:7777"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
