server:
  port: 80
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie
      routes:
        - id: ideas-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/ideas-service/**
        - id: scrum-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/scrum-service/**
        - id: authorization-service
          uri: http://localhost:7777
          predicates:
            - Path=/api/v1/authorization-service/**
        - id: notification-service
          uri: http://localhost:1337
          predicates:
            - Path=/api/v1/notification-service/**
        - id: email-service
          uri: http://localhost:3000
          predicates:
            - Path=/api/v1/email-service/**
        - id: tgbot-service
          uri: http://localhost:5321
          predicates:
            - Path=/api/v1/tgbot-service/**
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          spring:
            authorization-uri: http://127.0.0.1:7777/oauth2/authorize
            token-uri: http://127.0.0.1:7777/oauth2/token
            jwk-set-uri: http://127.0.0.1:7777/oauth2/jwks
