server:
  port: 80
spring:
  cloud:
    gateway:
      routes:
        - id: ideas-service
          uri: ${IDEAS_PATH:http://localhost:8082}
          predicates:
            - Path=/api/v1/ideas-service/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: scrum-service
          uri: ${SCRUM_PATH:http://localhost:8081}
          predicates:
            - Path=/api/v1/scrum-service/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: notification-service
          uri: ${NOTIFICATION_PATH:http://localhost:1337}
          predicates:
            - Path=/api/v1/notification-service/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost/login/oauth2/code/{registrationId}"
            scope: openid, resource.read
        provider:
          spring:
            issuer-uri: http://127.0.0.1:7777
