server:
  port: 80
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie
      routes:
        - id: ideas-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/ideas-service/**
        - id: scrum-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/scrum-service/**
        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/notification-service/**
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, resource.read
        provider:
          spring:
            issuer-uri: http://127.0.0.1:7777

