server:
  port: 80
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie
      routes:
        - id: ideas-service
          uri: http://ideas-service
          predicates:
            - Path=/api/v1/ideas-service/**
        - id: scrum-service
          uri: http://scrum-service
          predicates:
            - Path=/api/v1/scrum-service/**
        - id: authorization-service
          uri: http://authorization-service
          predicates:
            - Path=/api/v1/authorization-service/**
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: ${SERVICE_PASSWORD}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          spring:
            authorization-uri: http://authorization-service/oauth2/authorize
            token-uri: http://authorization-service/oauth2/token
            jwk-set-uri: http://authorization-service/oauth2/jwks

