package enums;

public enum NotificationCase {

    INITIATOR_INVITES_TEAM,
    TEAM_INVITE_IS_ACCEPTED,
    TEAM_INVITE_IS_CANCELLED,

    TEAM_OWNER_INVITES_USER,
    USER_SEND_REQUEST_TO_TEAM_OWNER,
    USER_ACCEPT_INVITE,
    USER_IS_KICKED_FROM_TEAM,
    USER_LEAVE_FROM_TEAM,
    TEAM_LEADER_CHANGES,
    INVITE_STATUS_IS_ACCEPTED,
    INVITE_STATUS_IS_CANCELED,
    REQUEST_IS_ACCEPTED,
    REQUEST_IS_CANCELED,
    TEAM_IS_DELETED
}
