server:
  port: 8084
authorization:
  host: https://hits1.tyuiu.ru
spring:
  rabbitmq:
    addresses: rabbitmq:5672
  mail:
    host: smtp.tsogu.ru
    port: 25
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    invitation: invitation.queue
  routing-keys:
    internal-invitation: internal.invitation.routing-key





