server:
  port: 8081
spring:
  r2dbc:
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30
    url: r2dbc:postgresql://localhost:5432/hits
    username: admin
    password: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:7777
          jwk-set-uri: http://127.0.0.1:7777/oauth2/jwks