name: GATEWAY

on:
  workflow_dispatch:
    branches:
      - go-to-prod
jobs:
  build-and-push-gateway:
    runs-on: ubuntu-latest
    env:
      SERVICE_PASSWORD: ${{ secrets.SERVICE_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Change wrapper permissions
        run: chmod +x ./api-gateway/gradlew

      - name: Build JAR file
        run:  | 
          cd api-gateway
          ./gradlew -Dtoken=${{ secrets.DOCKERHUB_TOKEN }} bootBuildImage

